################################################################################
#
#
# libretro-beetle-pcfx
################################################################################
# Version: Commits on Oct 22, 2024
LIBRETRO_BEETLE_PCFX_VERSION = dd04cef9355286488a1d78ff18c4c848a1575540
LIBRETRO_BEETLE_PCFX_SITE = $(call github,libretro,beetle-pcfx-libretro,$(LIBRETRO_BEETLE_PCFX_VERSION))
LIBRETRO_BEETLE_PCFX_LICENSE = GPLv2
LIBRETRO_BEETLE_PCFX_DEPENDENCIES += retroarch

# RK3566 is Cortex-A55. This Makefile's unix path sets ARCH_X86 from the
# host uname (SSE inline asm), so "unix arm64" dies in OwlResampler.
LIBRETRO_BEETLE_PCFX_PLATFORM = SM1

ifeq ($(BR2_PACKAGE_FLIP_NEVER)$(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = CortexA73_G12B
else ifeq ($(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = rpi4
else ifeq ($(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = rpi4
else ifeq ($(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = rpi5
else ifeq ($(BR2_PACKAGE_FLIP_NEVER)$(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = S905
else ifeq ($(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = S905
else ifeq ($(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = S905
else ifeq ($(BR2_PACKAGE_FLIP_NEVER)$(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = S905
else ifeq ($(BR2_PACKAGE_FLIP_NEVER)$(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = SM1
else ifeq ($(BR2_PACKAGE_FLIP_NEVER)$(BR2_PACKAGE_FLIP_NEVER)$(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = RK3588
else ifeq ($(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = armv
else ifeq ($(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = odin
else ifeq ($(BR2_PACKAGE_FLIP_NEVER)$(BR2_PACKAGE_FLIP_NEVER),y)
LIBRETRO_BEETLE_PCFX_PLATFORM = sm8250
endif

define LIBRETRO_BEETLE_PCFX_BUILD_CMDS
	$(TARGET_CONFIGURE_OPTS) $(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" \
	    -C $(@D) platform="$(LIBRETRO_BEETLE_PCFX_PLATFORM)" \
        GIT_VERSION="-$(shell echo $(LIBRETRO_BEETLE_PCFX_VERSION) | cut -c 1-7)"
endef

define LIBRETRO_BEETLE_PCFX_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/mednafen_pcfx_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/pcfx_libretro.so
endef

$(eval $(generic-package))
