[global]
	workgroup = WORKGROUP
	server string = Zlyme
	security = user
	map to guest = Bad User
	guest account = root
	disable netbios = yes
	load printers = no
	printcap name = /dev/null
	logging = 0

[storage]
	path = /storage
	browseable = yes
	writable = yes
	guest ok = yes
	force user = root
	create mask = 0644
	directory mask = 0755
