################################################################################
#
# dolphin-emu
#
# Knulli recipe, nogui + EGL DRM. No Qt, Wayland, or X11.
# BIOS path is /storage/Bios/GC (Knulli used /userdata/bios/GC).
################################################################################

DOLPHIN_EMU_VERSION = 805307f432dba079caf7339122a07de5b90c4b47
DOLPHIN_EMU_VERSION_MAJOR = 2503a
DOLPHIN_EMU_VERSION_MINOR = 328
DOLPHIN_EMU_SITE = https://github.com/dolphin-emu/dolphin
DOLPHIN_EMU_SITE_METHOD = git
DOLPHIN_EMU_LICENSE = GPL-2.0+
DOLPHIN_EMU_LICENSE_FILES = COPYING
DOLPHIN_EMU_GIT_SUBMODULES = YES
DOLPHIN_EMU_SUPPORTS_IN_SOURCE_BUILD = NO

DOLPHIN_EMU_DEPENDENCIES = libevdev ffmpeg zlib libpng lzo libusb libcurl
DOLPHIN_EMU_DEPENDENCIES += bluez5_utils hidapi xz host-xz sdl2 libdrm

DOLPHIN_EMU_CONF_OPTS  = -DCMAKE_BUILD_TYPE=Release
DOLPHIN_EMU_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
DOLPHIN_EMU_CONF_OPTS += -DDISTRIBUTOR='zlyme'
DOLPHIN_EMU_CONF_OPTS += -DUSE_DISCORD_PRESENCE=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_MGBA=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_UPNP=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_TESTS=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_AUTOUPDATE=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_ANALYTICS=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_SYSTEM_LIBS=AUTO
DOLPHIN_EMU_CONF_OPTS += -DUSE_SYSTEM_FMT=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_CLI_TOOL=OFF
DOLPHIN_EMU_CONF_OPTS += -DUSE_RETRO_ACHIEVEMENTS=ON
DOLPHIN_EMU_CONF_OPTS += -DENABLE_QT=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_NOGUI=ON
DOLPHIN_EMU_CONF_OPTS += -DENABLE_X11=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_WAYLAND=OFF
DOLPHIN_EMU_CONF_OPTS += -DENABLE_EGL=ON
# Host CMake 4 dropped <3.5. Externals/pugixml still asks for 3.3.
DOLPHIN_EMU_CONF_OPTS += -DCMAKE_POLICY_VERSION_MINIMUM=3.5

ifeq ($(BR2_PACKAGE_VULKAN_HEADERS)$(BR2_PACKAGE_VULKAN_LOADER),yy)
DOLPHIN_EMU_CONF_OPTS += -DENABLE_VULKAN=ON
DOLPHIN_EMU_DEPENDENCIES += vulkan-headers vulkan-loader
else
DOLPHIN_EMU_CONF_OPTS += -DENABLE_VULKAN=OFF
endif

DOLPHIN_EMU_MAKE_ENV += LDFLAGS="-Wl,--copy-dt-needed-entries"
DOLPHIN_EMU_CONF_ENV += LDFLAGS="-Wl,--copy-dt-needed-entries"

define DOLPHIN_EMU_PRE_CONFIGURE_HOOK
	sed -i 's/set(DOLPHIN_VERSION_MAJOR .*)/set(DOLPHIN_VERSION_MAJOR "$(DOLPHIN_EMU_VERSION_MAJOR)")/' \
		$(@D)/CMake/ScmRevGen.cmake
	sed -i 's/set(DOLPHIN_VERSION_MINOR .*)/set(DOLPHIN_VERSION_MINOR "$(DOLPHIN_EMU_VERSION_MINOR)")/' \
		$(@D)/CMake/ScmRevGen.cmake
endef

DOLPHIN_EMU_PRE_CONFIGURE_HOOKS = DOLPHIN_EMU_PRE_CONFIGURE_HOOK

define DOLPHIN_EMU_INSTALL_WRAPPER
	$(INSTALL) -D -m 0755 $(DOLPHIN_EMU_PKGDIR)/start_dolphin.sh \
		$(TARGET_DIR)/usr/bin/start_dolphin
endef

DOLPHIN_EMU_POST_INSTALL_TARGET_HOOKS += DOLPHIN_EMU_INSTALL_WRAPPER

$(eval $(cmake-package))
